### ISSUE TITLE
TapoError.ERR_PARAMS when brightness value is 1

### ISSUE THREAD

**Issue by zanna-37** [petretiandrea/plugp100#101]
I'm using a Tapo L520. And the following service call returns an error.
Other brightness values work as expected.

```yaml
service: light.turn_on
data:
  brightness: 1
target:
  entity_id: light.back_terrace_light
```

The error is:
Unexpected error for call_service at pos 1: Returned error_code: TapoError.ERR_PARAMS: Request params error
